draw_self()
draw_text(x,y-32,string(canOrb))
draw_text(x,y-42,string(thrown_orb))
draw_text(x,y-52,string(state))

draw_set_color(c_aqua)
draw_line(bbox_left,bbox_top,bbox_right,bbox_top)
draw_line(bbox_right,bbox_top,bbox_right,bbox_bottom)
draw_line(bbox_left,bbox_bottom,bbox_right,bbox_bottom)
draw_line(bbox_left,bbox_top,bbox_left,bbox_bottom)